### ISSUE TITLE
UI update period should be less than the physics update period

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-websim#12]
The physics update period is currently set to 25ms. The UI should probably only update it's output at no less than 100ms to save on CPU. Additionally, the following optimizations should be made:

* Cache the jQuery/bootstrap sliders/elements so you don't have to search for them each time would be good
* Only changing the values if the values updated

It's possible that your refactor has fixed some of these already.

**Comment by amorygalili** [comment]
Done.

**Comment by virtuald** [comment]
Fixed where? Definitely not done.

**Comment by amorygalili** [comment]
Should be done now. The jQuery elements I think are all cached and the values are only updated when the ui is interacted with.
