### ISSUE TITLE
Module position information should be written to user-config.json

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-websim#18]
When multiple people are working on robot code, they may have individual preferences about how the modules are positioned (in particular, if they have different monitor sizes). Currently this data is written to config.json, which holds information that everyone needs.

Write the position information to user-config.json instead of config.json, that way one could add user-config.json to .gitignore, allowing multiple users to have their own preferred layouts.

**Comment by amorygalili** [comment]
Done

**Comment by amorygalili** [comment]
Need to do this for the new websim.
