### ISSUE TITLE
When I press '0', the sliders should set the current value to zero

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-websim#20]
And the same for other numbers too.

**Comment by amorygalili** [comment]
Doesn't it already do that? Or do you mean make some easy way of setting the value to 0?

**Comment by virtuald** [comment]
It does not do it for me.

**Comment by amorygalili** [comment]
Done.

**Comment by amorygalili** [comment]
Need to add this feature to the new websim.
