### ISSUE TITLE
When I click the header of each module, it immediately goes into absolute position mode

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-websim#22]
Should probably wait until I actually move the mouse. 

It would be nice if I could get it out of absolute position mode, or if there was a reflow option.

**Comment by virtuald** [comment]
The absolute position mode stuff was very confusing for my students when we ran it today.

**Comment by amorygalili** [comment]
No longer an issue because you have to go to the config menu to switch to absolute positioning.
