### ISSUE TITLE
Physics implementation

### ISSUE THREAD

**Issue by amorygalili** [robotpy/robotpy-websim#5]
Has robot physics been implemented on the server? I need to get things like robot position and heading in order to make an animation in the html interface.

**Comment by virtuald** [comment]
I would focus on animating the following simple motions instead:

* circular motion, as driven by a motor (perhaps with encoder output, and with a limit switch somewhere?)
* linear motion, as driven by a motor (with limit switches for positions)

Then... we figure out the best way for the user to configure this stuff?

**Comment by amorygalili** [comment]
Are these general animations that can be used for many things, or are they more specific, like animation specific to an encoder that happens to use a circular motion?

**Comment by virtuald** [comment]
I was hoping to have some kind of simple thing that you could setup a config to say "setup a circular motion and attach it to jaguar 1", without having to know how to animate things yourself.

**Comment by amorygalili** [comment]
Is this actually an animation, or could it be something that's periodically sending position/rotation information to observers?

**Comment by virtuald** [comment]
I don't really see a difference between the two.

**Comment by amorygalili** [comment]
Well I wasn't sure if by animation you meant that it would actually display the motion itself or if it would send data to some listener which would take care of the actual visual effect.

**Comment by virtuald** [comment]
That sounds like an implementation detail.
