### ISSUE TITLE
Gamepad/joystick support?

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-websim#7]
Looks like it's mainstream: https://developer.mozilla.org/en-US/docs/Web/Guide/API/Gamepad

**Comment by amorygalili** [comment]
It would be pretty cool if we could set values with joysticks instead of having to move a slider. I'll mess around with this when I get the chance.

**Comment by amorygalili** [comment]
Added support for this. Tested it with an xbox one controller and it worked. My switch pro controller didn't though, so some controllers aren't supported. It also sees POV as button values, and I don't think there's an easy way to figure out which buttons map to POV.
